#-----------------------------------------------------------------------------
# paises_iso_continente.R
#-----------------------------------------------------------------------------
#   ISO codes and continent lookup used to join Wikidata castle countries.
#-----------------------------------------------------------------------------

paises_iso_continente <- data.frame(
  pais = c("Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia-Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras", "Congo", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Esuatini", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea", "Guinea Ecuatorial", "Guinea-Bisáu", "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Palestina", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Taiwán", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Vaticano", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue", "Inglaterra", "Escocia", "Gales", "Irlanda del Norte", "Gibraltar", "Islas Feroe", "Isla de Man", "Curazao", "Guernsey", "Jersey", "Aruba", "Sint Maarten"),
  iso = c("AF", "AL", "DE", "AD", "AO", "AG", "SA", "DZ", "AR", "AM", "AU", "AT", "AZ", "BS", "BD", "BB", "BH", "BE", "BZ", "BJ", "BY", "MM", "BO", "BA", "BW", "BR", "BN", "BG", "BF", "BI", "BT", "CV", "KH", "CM", "CA", "QA", "TD", "CL", "CN", "CY", "CO", "KM", "CG", "KP", "KR", "CI", "CR", "HR", "CU", "DK", "DM", "EC", "EG", "SV", "AE", "ER", "SK", "SI", "ES", "US", "EE", "SZ", "ET", "PH", "FI", "FJ", "FR", "GA", "GM", "GE", "GH", "GD", "GR", "GT", "GN", "GQ", "GW", "GY", "HT", "HN", "HU", "IN", "ID", "IQ", "IR", "IE", "IS", "MH", "SB", "IL", "IT", "JM", "JP", "JO", "KZ", "KE", "KG", "KI", "XK", "KW", "LA", "LS", "LV", "LB", "LR", "LY", "LI", "LT", "LU", "MK", "MG", "MY", "MW", "MV", "ML", "MT", "MA", "MU", "MR", "MX", "FM", "MD", "MC", "MN", "ME", "MZ", "NA", "NR", "NP", "NI", "NE", "NG", "NO", "NZ", "OM", "NL", "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PL", "PT", "GB", "CF", "CZ", "CD", "DO", "RW", "RO", "RU", "WS", "KN", "SM", "VC", "LC", "ST", "SN", "RS", "SC", "SL", "SG", "SY", "SO", "LK", "ZA", "SD", "SS", "SE", "CH", "SR", "TH", "TW", "TZ", "TJ", "TL", "TG", "TO", "TT", "TN", "TM", "TR", "TV", "UA", "UG", "UY", "UZ", "VU", "VA", "VE", "VN", "YE", "DJ", "ZM", "ZW", "GB-ENG", "GB-SCT", "GB-WLS", "GB-NIR", "GI", "FO", "IM", "CW", "GG", "JE", "AW", "SX"),
  iso_3 = c("AFG", "ALB", "DEU", "AND", "AGO", "ATG", "SAU", "DZA", "ARG", "ARM", "AUS", "AUT", "AZE", "BHS", "BGD", "BRB", "BHR", "BEL", "BLZ", "BEN", "BLR", "MMR", "BOL", "BIH", "BWA", "BRA", "BRN", "BGR", "BFA", "BDI", "BTN", "CPV", "KHM", "CMR", "CAN", "QAT", "TCD", "CHL", "CHN", "CYP", "COL", "COM", "COG", "PRK", "KOR", "CIV", "CRI", "HRV", "CUB", "DNK", "DMA", "ECU", "EGY", "SLV", "ARE", "ERI", "SVK", "SVN", "ESP", "USA", "EST", "SWZ", "ETH", "PHL", "FIN", "FJI", "FRA", "GAB", "GMB", "GEO", "GHA", "GRD", "GRC", "GTM", "GIN", "GNQ", "GNB", "GUY", "HTI", "HND", "HUN", "IND", "IDN", "IRQ", "IRN", "IRL", "ISL", "MHL", "SLB", "ISR", "ITA", "JAM", "JPN", "JOR", "KAZ", "KEN", "KGZ", "KIR", "—", "KWT", "LAO", "LSO", "LVA", "LBN", "LBR", "LBY", "LIE", "LTU", "LUX", "MKD", "MDG", "MYS", "MWI", "MDV", "MLI", "MLT", "MAR", "MUS", "MRT", "MEX", "FSM", "MDA", "MCO", "MNG", "MNE", "MOZ", "NAM", "NRU", "NPL", "NIC", "NER", "NGA", "NOR", "NZL", "OMN", "NLD", "PAK", "PLW", "PSE", "PAN", "PNG", "PRY", "PER", "POL", "PRT", "GBR", "CAF", "CZE", "COD", "DOM", "RWA", "ROU", "RUS", "WSM", "KNA", "SMR", "VCT", "LCA", "STP", "SEN", "SRB", "SYC", "SLE", "SGP", "SYR", "SOM", "LKA", "ZAF", "SDN", "SSD", "SWE", "CHE", "SUR", "THA", "TWN", "TZA", "TJK", "TLS", "TGO", "TON", "TTO", "TUN", "TKM", "TUR", "TUV", "UKR", "UGA", "URY", "UZB", "VUT", "VAT", "VEN", "VNM", "YEM", "DJI", "ZMB", "ZWE", "", "", "", "", "GIB", "FRO", "IMN", "CUW", "GGY", "JEY", "ABW", "SXM"),
  continent = c("Asia", "Europa", "Europa", "Europa", "África", "América", "Asia", "África", "América", "Asia", "Oceanía", "Europa", "Asia", "América", "Asia", "América", "Asia", "Europa", "América", "África", "Europa", "Asia", "América", "Europa", "África", "América", "Asia", "Europa", "África", "África", "Asia", "África", "Asia", "África", "América", "Asia", "África", "América", "Asia", "Europa", "América", "África", "África", "Asia", "Asia", "África", "América", "Europa", "América", "Europa", "América", "América", "África", "América", "Asia", "África", "Europa", "Europa", "Europa", "América", "Europa", "África", "África", "Asia", "Europa", "Oceanía", "Europa", "África", "África", "Asia", "África", "América", "Europa", "América", "África", "África", "África", "América", "América", "América", "Europa", "Asia", "Asia", "Asia", "Asia", "Europa", "Europa", "Oceanía", "Oceanía", "Asia", "Europa", "América", "Asia", "Asia", "Asia", "África", "Asia", "Oceanía", "Europa", "Asia", "Asia", "África", "Europa", "Asia", "África", "África", "Europa", "Europa", "Europa", "Europa", "África", "Asia", "África", "Asia", "África", "Europa", "África", "África", "África", "América", "Oceanía", "Europa", "Europa", "Asia", "Europa", "África", "África", "Oceanía", "Asia", "América", "África", "África", "Europa", "Oceanía", "Asia", "Europa", "Asia", "Oceanía", "Asia", "América", "Oceanía", "América", "América", "Europa", "Europa", "Europa", "África", "Europa", "África", "América", "África", "Europa", "Europa", "Oceanía", "América", "Europa", "América", "América", "África", "África", "Europa", "África", "África", "Asia", "Asia", "África", "Asia", "África", "África", "África", "Europa", "Europa", "América", "Asia", "Asia", "África", "Asia", "Oceanía", "África", "Oceanía", "América", "África", "Asia", "Asia", "Oceanía", "Europa", "África", "América", "Asia", "Oceanía", "Europa", "América", "Asia", "Asia", "África", "África", "África", "Europa", "Europa", "Europa", "Europa", "Europa", "Europa", "Europa", "América", "Europa", "Europa", "América", "América"),
  stringsAsFactors = FALSE
)

#-----------------------------------------------------------------------------
# End of paises_iso_continente.R
#-----------------------------------------------------------------------------
